- 0
- 3  # Bembelbots
- 4  # Berlin United
- 5  # B-Human
- 8  # Dutch Nao Team
- 12  # Nao Devils
- 13  # HTWK Robots
- 19  # SPQR Team
- 24  # HULKs
- 45  # Naova
- 50  # R-ZWEI KICKERS
- 70  # B-Team
