- 0
- 3  # Bembelbots
- 4  # Berlin United
- 5  # B-Human
- 8  # Dutch Nao Team
- 12  # Nao Devils
- 13  # HTWK Robots
- 17  # RoboEireann
- 18  # rUNSWift
- 19  # SPQR Team
- 24  # HULKs
- 31  # UnBeatables
- 33  # NomadZ
- 45  # Naova
- 47  # Rinobot-Jaguar
- 49  # SABANA Herons
- 50  # R-ZWEI KICKERS
- 51  # RedBackBots
- 53  # RoboIME
- 54  # WisTex United
- 70  # B-Team
