- 0
- 8  # Dutch Nao Team
- 31  # UnBeatables
- 45  # Naova
- 47  # Rinobot-Jaguar
- 49  # SABANA Herons
- 50  # R-ZWEI KICKERS
- 51  # RedBackBots
- 53  # RoboIME
- 54  # WisTex United
- 70  # B-Team
