name: Make Distribution

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y libclang-dev libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev
          dist/mkdist-linux ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist-ubuntu-22.04
          path: |
            dist/*.tar.bz2
