name: Make Distribution

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-22.04
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - if: ${{ matrix.os == 'macos-latest' }}
        run: |
          rustup target add aarch64-apple-darwin x86_64-apple-darwin
          dist/mkdist-macos ${{ github.ref_name }}
      - if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libayatana-appindicator3-dev libclang-dev librsvg2-dev libwebkit2gtk-4.1-dev libxdo-dev
          dist/mkdist-linux ${{ github.ref_name }}
      - if: ${{ matrix.os == 'windows-latest' }}
        run: |
          dist/mkdist-windows.ps1 ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: |
            dist/*.dmg
            dist/*.tar.bz2
            dist/*.zip
